/**
 * Created to keep constants here.
 * @author Alessandro Pio Ardizio
 * @since 0.1
 */
'use strict'

const NODE_ADDED = 'NODE_ADDED'
const NODE_REMOVED = 'NODE_REMOVED'
const HEART_BEAT = 'HEART_BEAT'
const WELCOME = 'WELCOME'
const RECONNECT = 'RECONNECT'
const BOOTSTRAP = 'BOOTSTRAP'
const MESSAGE_SEPARATOR = '?!£$=?!'
const BECOME_LEADER = 'BECOME_LEADER'
const PARTITIONS_ASSIGNED = 'PARTITIONS_ASSIGNED'
const PARTITIONS_REVOKED = 'PARTITIONS_REVOKED'
const PARTITION_CHANGE = 'PARTITION_CHANGE'
const LOCAL_QUORUM_REPLICATION = 'LOCAL_QUORUM'
const QUORUM_REPLICATION = 'QUORUM_REPLICATION'
const TOTAL_REPLICATION = 'TOTAL_REPLICATION'

module.exports = {
  NODE_ADDED: NODE_ADDED,
  NODE_REMOVED: NODE_REMOVED,
  WELCOME: WELCOME,
  RECONNECT: RECONNECT,
  BOOTSTRAP: BOOTSTRAP,
  MESSAGE_SEPARATOR: MESSAGE_SEPARATOR,
  HEART_BEAT: HEART_BEAT,
  BECOME_LEADER: BECOME_LEADER,
  PARTITIONS_ASSIGNED: PARTITIONS_ASSIGNED,
  PARTITIONS_REVOKED: PARTITIONS_REVOKED,
  PARTITION_CHANGE: PARTITION_CHANGE,
  LOCAL_QUORUM_REPLICATION: LOCAL_QUORUM_REPLICATION,
  QUORUM_REPLICATION: QUORUM_REPLICATION,
  TOTAL_REPLICATION: TOTAL_REPLICATION
}
